Repository Yashkapure06/GDSC-ProCode, pull requests merged in 2022-10, with the labels that each got.

#79 Create Chinmay_chaudhari.java
  2022-Oct/01 Oct 2022/Chinmay_chaudhari.java
Labels: hacktoberfest-accepted

#81 sarang_more
  2022-Oct/01 Oct 2022/sarang_more.py
  sarang_more.py
Labels: hacktoberfest-accepted

#80 Prathamesh_Patil.py
  2022-Oct/01 Oct 2022/palindrome.py
Labels: Invalid File Name

#95 Created Kunal_Nandre.java
  2022-Oct/02 Oct 2022/Kunal_Nandre.java
Labels: hacktoberfest-accepted

#132 Abhishek_Srivastava.cpp
  2022-Oct/04 Oct 2022/Abhishek_Srivastava.cpp
Labels: Invalid File Name

#138 Rushikesh_Bhalerao.cpp
  2022-Oct/02 Oct 2022/Rushikesh_Bhalerao.py
  2022-Oct/03 Oct 2022/Rushikesh_Bhalerao.cpp
  2022-Oct/04 Oct 2022/Rushikesh_Bhalerao.py
  2022-Oct/05 Oct 2022/Rushikesh_Bhalerao.py
Labels: Uploaded at wrong path

#142 longest word in a string created by HarshSuhane
  2022-Oct/05 Oct 2022/HARSH_SUHANE.c
Labels: hacktoberfest-accepted

#141 Create kartikey_singh.cpp
  2022-Oct/05 Oct 2022/kartikey_singh.cpp
Labels: hacktoberfest-accepted

#143 two strings are anagram or not created HARSHSUHANE
  2022-Oct/04 Oct 2022/HARSH_SUHANE.js
Labels: hacktoberfest-accepted

#144 Kunal_Nandre.java
  2022-Oct/04 Oct 2022/Kunal_Nandre.java
Labels: hacktoberfest-accepted

#147 convert uppercase letters to lower case and vice versa in string created by HARSHSUHANE
  2022-Oct/02 Oct 2022/HARSH_SUHANE.c
  2022-Oct/03 Oct 2022/HARSH_SUHANE.c
Labels: hacktoberfest-accepted

#148 calculate capital letters in a string created by HARSHSUHANE
  2022-Oct/02 Oct 2022/HARSH_SUHANE.c
Labels: duplicate, hacktoberfest-accepted

#159 Add solution for OCT 5 by Isuru Gunarathne
  2022-Oct/05 Oct 2022/Isuru_Gunarathne.py
Labels: hacktoberfest-accepted

#157 Create Abhishek_Srivastava.cpp
  2022-Oct/05 Oct 2022/Abhishek_Srivastava.cpp
Labels: hacktoberfest-accepted

#176 added javascript solutions for the programming problem
  2022-Oct/05 Oct 2022/Johnnie_Emmanuel.js
  2022-Oct/06 Oct 2022/Johnnie_Emmanuel.js
Labels: hacktoberfest-accepted

#166 Create by Akanksha_Talele.java
  2022-Oct/01 Oct 2022/Akanksha_Talele.java
  2022-Oct/02 Oct 2022/Akanksha_Talele.java
Labels: hacktoberfest-accepted

#192 Problem Statement - > 07 Oct 2022
  2022-Oct/05 Oct 2022/README.md
  2022-Oct/06 Oct 2022/README.md
  2022-Oct/07 Oct 2022/README.md
Labels: hacktoberfest-accepted

#206 Longest Palindrome Created by joelsathi
  2022-Oct/07 Oct 2022/joel_sathiyendra.py
Labels: hacktoberfest-accepted

#196 Added solution for 7th Oct in python
  2022-Oct/07 Oct 2022/mayur_joshi.py
Labels: hacktoberfest-accepted

#200 Create Madhav_Gupta.cpp
  2022-Oct/06 Oct 2022/Madhav_Gupta.cpp
Labels: hacktoberfest-accepted

#197 sarang more
  2022-Oct/06 Oct 2022/sarang_more.py
Labels: hacktoberfest-accepted

#195 Accept a string from user and Return LARGEST PALINDROME word from it.Created by AdityaSingh.
  2022-Oct/07 Oct 2022/Aditya_Singh.cpp
Labels: hacktoberfest-accepted

#207 added the javascript solution for the palindrome problem for 7th oct
  2022-Oct/07 Oct 2022/Johnnie_Emmanuel.js
Labels: hacktoberfest-accepted

#223 6th OCT Made in JS by Kashti Sharma
  2022-Oct/06 Oct 2022/kashti_sharma.js
Labels: hacktoberfest-accepted

#225 Created by vaishnavi_kapadi
  2022-Oct/07 Oct 2022/Vaishnavi_kapadi.cpp
Labels: hacktoberfest-accepted

#227 Added code for 7 oct 2022
  2022-Oct/07 Oct 2022/rucha_kale.py
Labels: hacktoberfest-accepted

#226 Added code for 7th Oct
  2022-Oct/07 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#262 Kunal_Nandre.java
  2022-Oct/08 Oct 2022/Kunal_Nandre.java
Labels: hacktoberfest-accepted

#264 Renamed according to requirement
  2022-Oct/04 Oct 2022/Tanmay_Badhe.cpp
  2022-Oct/05 Oct 2022/Shivank_Singh.py
  2022-Oct/05 Oct 2022/Tanmay_Badhe.cpp
  2022-Oct/07 Oct 2022/joel_sathiyendra.py
Labels: hacktoberfest-accepted

#296 8th Oct '22 by Kashti Sharma
  2022-Oct/08 Oct 2022/kashti_sharma.py
Labels: hacktoberfest-accepted

#297 7th Oct'22 by Kashti Sharma
  2022-Oct/07 Oct 2022/kashti_sharma.py
Labels: hacktoberfest-accepted

#300 Added code for 1 oct
  2022-Oct/01 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#301 Added code for 2nd oct
  2022-Oct/02 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#302 Added code for day 3
  2022-Oct/03 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#303 Added code for 4th Oct
  2022-Oct/04 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#310 Code of 1 oct 2022
  2022-Oct/01 Oct 2022/rucha_kale.py
Labels: hacktoberfest-accepted

#311 Create atharva_kawale.py
  2022-Oct/11 Oct 2022/atharva_kawale.py
Labels: hacktoberfest-accepted

#309 11th Oct'22 Created by Shrutika Hilale
  2022-Oct/11 Oct 2022/shrutika_hilale.cpp
Labels: hacktoberfest-accepted

#308 Add 11 Oct solution
  2022-Oct/09 Oct 2022/Sai_Manoj_Etcherla.cpp
  2022-Oct/11 Oct 2022/Sai_Manoj_Etcherla.cpp
Labels: hacktoberfest-accepted

#305 Created by Atharva Kasodekar
  2022-Oct/03 Oct 2022/Atharva_Kasodekar.cpp
Labels: hacktoberfest-accepted

#299 rushikesh_darunte.py
  2022-Oct/08 Oct 2022/rushikesh_darunte.py
Labels: hacktoberfest-accepted

#294 Lettymoon2
  2022-Oct/01 Oct 2022/lettymoon.hs
  2022-Oct/02 Oct 2022/lettymoon.hs
Labels: hacktoberfest-accepted

#304 9 Oct 2022 sol (golang)
  2022-Oct/09 Oct 2022/risiraj_dey.go
Labels: hacktoberfest-accepted

#307 Added 11 Oct Problem Solution in C++
  2022-Oct/11 Oct 2022/Deepak_Kumar.cpp
Labels: hacktoberfest-accepted

#306 add solution for 09-Oct-2022
  2022-Oct/09 Oct 2022/Aryan_V_S.cpp
Labels: hacktoberfest-accepted

#285 Create Madhav_Gupta.js
  2022-Oct/08 Oct 2022/Madhav_Gupta.js
Labels: hacktoberfest-accepted

#281 Aditya_salve.cpp
  2022-Oct/06 Oct 2022/Aditya_salve.cpp
Labels: hacktoberfest-accepted

#315 Create GDSC.java
  2022-Oct/11 Oct 2022/GDSC.java
Labels: hacktoberfest-accepted

#286 Create Madhav_Gupta.cpp
  2022-Oct/08 Oct 2022/Madhav_Gupta.cpp
Labels: hacktoberfest-accepted

#314 Create Amaan_Sayyed.py largest pali check program
  2022-Oct/07 Oct 2022/Amaan_Sayyed.py
Labels: hacktoberfest-accepted

#317 Update and rename GDSC.java to Hemant_Modi.java
  2022-Oct/11 Oct 2022/Hemant_Modi.java
Labels: hacktoberfest-accepted

#292 Kunal_Nandre.java
  2022-Oct/09 Oct 2022/Kunal_Nandre.java
Labels: hacktoberfest-accepted

#282 Solution submitted by Aditya Sai
  2022-Oct/06 Oct 2022/aditya_sai.py
Labels: hacktoberfest-accepted

#279 Accept a string from user and Print all Cobinations of it. Created by…
  2022-Oct/09 Oct 2022/Aditya_SinghKushwaha.cpp
Labels: hacktoberfest-accepted

#270 Created by Aditya Sai
  2022-Oct/09 Oct 2022/aditya_sai.cpp
Labels: hacktoberfest-accepted

#328 added code for 2nd oct
  2022-Oct/02 Oct 2022/gaurav_lad.py
Labels: hacktoberfest-accepted

#332 created by jain garima
  2022-Oct/04 Oct 2022/garimajain.java
Labels: hacktoberfest-accepted

#331 Problem solved for 11th october in python
  2022-Oct/11 Oct 2022/avani_11.py
Labels: hacktoberfest-accepted

#330 created by sejal_shingote of 1st oct
  2022-Oct/01 Oct 2022/sejal_shingote.py
  2022-Oct/04 Oct 2022/sejal_shingote.c
Labels: hacktoberfest-accepted

#329 created for 1st oct by shantanu chinchle
  2022-Oct/01 Oct 2022/shantanu_chinchle.c
  2022-Oct/02 Oct 2022/shantanu_chinchle.py
Labels: hacktoberfest-accepted

#327 Added code for 9th oct by vaishnavi Kapadi
  2022-Oct/09 Oct 2022/vaishnavi_kapadi.cpp
Labels: hacktoberfest-accepted

#333 created by sejal_shingote for 7 oct
  2022-Oct/07 Oct 2022/sejal_shingote.py
Labels: hacktoberfest-accepted

#335 created by sejal_shingote
  2022-Oct/08 Oct 2022/sejal_shingote.py
Labels: hacktoberfest-accepted

#334 created by gj
  2022-Oct/02 Oct 2022/garimajaiin.py
Labels: hacktoberfest-accepted

#336 created by gj
  2022-Oct/01 Oct 2022/garimajain.py
  2022-Oct/08 Oct 2022/garimajain.py
Labels: hacktoberfest-accepted

#338 Created by mohee athani
  2022-Oct/08 Oct 2022/mohee_athani.py
Labels: hacktoberfest-accepted

#341 Create rucha_kale.py
  2022-Oct/02 Oct 2022/rucha_kale.py
  2022-Oct/03 Oct 2022/rucha_kale.py
Labels: hacktoberfest-accepted

#342 Solution for 12th oct PS- Sumant Chaudhary
  .vscode/settings.json
  2022-Oct/12 Oct 2022/sumant_chaudhary.cpp
Labels: hacktoberfest-accepted

#366 Create Akanksha_Talele.java
  2022-Oct/04 Oct 2022/Akanksha_Talele.java
Labels: hacktoberfest-accepted

#369 Palindrome in Golang by Hariraj
  2022-Oct/01 Oct 2022/Hariraj_Arunachalam.go
Labels: hacktoberfest-accepted

#340 Created by Akanksha Talele.
  2022-Oct/02 Oct 2022/Akanksha_Talele1.java
  2022-Oct/03 Oct 2022/Akanksha_Talele3.java
  2022-Oct/04 Oct 2022/Akanksha_Talele4.java
  2022-Oct/05 Oct 2022/Akanksha_Talele5.java
  2022-Oct/06 Oct 2022/Akanksha_Talele6.java
Labels: hacktoberfest-accepted

#339 CREATED BY MOHEE ATHANI
  2022-Oct/09 Oct 2022/mohee_athani.cpp
  2022-Oct/11 Oct 2022/mohee_athani.py
Labels: hacktoberfest-accepted

#372 Create Aaditya_burujwale.js
  2022-Oct/13 Oct 2022/Aaditya_burujwale.js
Labels: hacktoberfest-accepted

#320 Added java solution for problem statement 11/10/22
  2022-Oct/11 Oct 2022/riya_gupta.java
Labels: hacktoberfest-accepted

#325 Create Mansingh_Shekhawat.c
  2022-Oct/09 Oct 2022/Mansingh_Shekhawat.c
Labels: hacktoberfest-accepted

#321 11 Oct Solution Created by P J Joseph & Deletion
  2022-Oct/11 Oct 2022/pj_joseph.java
  2022-Sept/27 Sept 2022/Shubham_Sanap.cpp
Labels: hacktoberfest-accepted

#370 Problem13 Created by Nitin Diwakar
  2022-Oct/13 Oct 2022/nitin_diwakar.py
Labels: hacktoberfest-accepted

#367 Create Mansingh_Shekhawat.py
  2022-Oct/13 Oct 2022/Mansingh_Shekhawat.py
Labels: hacktoberfest-accepted

#379 Code added for 5th Oct
  2022-Oct/05 Oct 2022/isha_vaidya.py
  2022-Oct/06 Oct 2022/isha_vaidya.py
Labels: hacktoberfest-accepted

#394 Create avani_11.py
  2022-Oct/12 Oct 2022/avani_11.py
Labels: hacktoberfest-accepted

#392 Create avani_11.py
  2022-Oct/13 Oct 2022/avani_11.py
Labels: hacktoberfest-accepted

#400 adding solution for 16oct.
  2022-Oct/16 Oct 2022/TanyaAhuja16oct.cpp
Labels: hacktoberfest-accepted

#409 solution 16 OCT using C
  2022-Oct/16 Oct 2022/RaghvendraTiwari16oct.c
  2022-Oct/16 Oct 2022/RaghvendraTiwari16oct.exe
Labels: hacktoberfest-accepted

#408 Create AvaniWani_11.py
  2022-Oct/15 Oct 2022/AvaniWani_11.py
Labels: hacktoberfest-accepted

#407 add 2 2D array by Venkat Swaraj
  2022-Oct/16 Oct 2022/venkat_swaraj.py
Labels: hacktoberfest-accepted

#406 Add 16 Oct Solution
  2022-Oct/15 Oct 2022/Sai_Manoj_Etcherla.cpp
  2022-Oct/16 Oct 2022/Sai_Manoj_Etcherla.cpp
Labels: hacktoberfest-accepted

#405 Rotating array by D times Created by Venkat Swaraj
  2022-Oct/15 Oct 2022/venkat_swaraj.py
Labels: hacktoberfest-accepted

#404 Solution to problem of 16/10/2022.cpp
  2022-Oct/16 Oct 2022/Tusshar_Paul.cpp
Labels: hacktoberfest-accepted

#403 Create CPP-solution.cpp
  2022-Oct/16 Oct 2022/CPP-solution.cpp
Labels: hacktoberfest-accepted

#402 Java Solution of Add Two 2D Array
  2022-Oct/16 Oct 2022/RatiJindal.java
Labels: hacktoberfest-accepted

#401 16th October solution Created by Aman Raj
  2022-Oct/16 Oct 2022/Aman_Raj.c
Labels: hacktoberfest-accepted

#399 Kunal_Nandre.java
  2022-Oct/15 Oct 2022/Kunal_Nandre.java
Labels: hacktoberfest-accepted

#398 Validate anagram using Golang by Hariraj
  2022-Oct/04 Oct 2022/Hariraj_Arunachalam.go
Labels: hacktoberfest-accepted

#397 Added golang code for 15th october problem statement.
  2022-Oct/15 Oct 2022/Nikit.go
Labels: hacktoberfest-accepted

#396 October 15th Created by Michael Giardina
  2022-Oct/15 Oct 2022/Michael_Giardina.py
Labels: hacktoberfest-accepted

#393 No. of palindrome created by Shubham_Sanap
  2022-Oct/11 Oct 2022/shubham_sanap.py
  2022-Oct/12 Oct 2022/shubham_sanap.py
Labels: hacktoberfest-accepted

#391 October 15th solution Created by Aman Raj
  2022-Oct/15 Oct 2022/Aman_Raj.c
Labels: hacktoberfest-accepted

#389 Calculate capital letters in Golang By Hariraj
  2022-Oct/02 Oct 2022/Hariraj_Arunachalam.go
Labels: hacktoberfest-accepted

#416 Creating Chathura_Gunasekara.py
  2022-Oct/16 Oct 2022/Chathura_Gunasekara.py
Labels: hacktoberfest-accepted

#385 Create Sahil_kumar_singh.cpp
  2022-Oct/15 Oct 2022/Sahil_kumar_singh.cpp
Labels: hacktoberfest-accepted

#421 code added for 12th oct by gl
  2022-Oct/12 Oct 2022/Gaurav_Lad_03
Labels: hacktoberfest-accepted

#442 OCT 1
  2022-Oct/01 Oct 2022/rajashri.py
Labels: hacktoberfest-accepted

#443 Code for 11th Oct
  2022-Oct/11 Oct 2022/rajashri.py
Labels: hacktoberfest-accepted

#444 Code for 13th OCT
  2022-Oct/13 Oct 2022/rajashri.py
Labels: hacktoberfest-accepted

#441 Added code for transpose of matrix 18October
  2022-Oct/18 Oct 2022/vaibhav_joshi.cpp
Labels: hacktoberfest-accepted

#422 created by gl for 12th octt
  2022-Oct/13 Oct 2022/Gaurav_Lad_04.py
  2022-Oct/16 Oct 2022/Gaurav_Lad_05.py
Labels: hacktoberfest-accepted

#445 Code for 5th Oct
  2022-Oct/05 Oct 2022/rajashri.py
Labels: hacktoberfest-accepted

#446 Code created by GL for 18th oct
  2022-Oct/18 Oct 2022/Gaurav_Lad_06.py
Labels: hacktoberfest-accepted

#449 created by Gaurav_G for1st oct
  2022-Oct/01 Oct 2022/gaurav_gulahe.java
  2022-Oct/16 Oct 2022/Gaurav_Gulahe.py
Labels: hacktoberfest-accepted

#448 13th oct by Vaishnavi
  2022-Oct/13 Oct 2022/vaishnavi_kapadi.cpp
Labels: hacktoberfest-accepted

#418 Create Yogita_Nikam.java
  2022-Oct/01 Oct 2022/Yogita_Nikam.java
  2022-Oct/02 Oct 2022/Yogita_Nikam.java
  2022-Oct/03 Oct 2022/Yogita_Nikam.java
  2022-Oct/04 Oct 2022/Yogita_Nikam.java
  2022-Oct/05 Oct 2022/Yogita_Nikam.java
  2022-Oct/06 Oct 2022/Yogita_Nikam.py
  2022-Oct/07 Oct 2022/Yogita_Nikam.cpp
  2022-Oct/08 Oct 2022/Yogita_Nikam.py
  2022-Oct/16 Oct 2022/Yogita_Nikam.cpp
  2022-Oct/18 Oct 2022/Yogita_nikam.java
Labels: hacktoberfest-accepted

#425 Tanmay_Badhe.cpp
  2022-Oct/16 Oct 2022/Tanmay_Badhe.cpp
Labels: hacktoberfest-accepted

#437 Create Keshav_Kumar.cpp
  2022-Oct/15 Oct 2022/Keshav_Kumar.cpp
Labels: hacktoberfest-accepted

#390 Case conversion by Hariraj In Golang
  2022-Oct/03 Oct 2022/Hariraj_Arunachalam.go
Labels: hacktoberfest-accepted

#433 Java Solution of Transpose a 2D Array
  2022-Oct/18 Oct 2022/RatiJindal.java
Labels: hacktoberfest-accepted

#387 Added python solution for problem 15/10/22
  2022-Oct/15 Oct 2022/deepesh_kumar.py
Labels: hacktoberfest-accepted

#386 Solution to Problem of 15/10/2022 added.cpp
  2022-Oct/15 Oct 2022/Tusshar_Paul.cpp
Labels: hacktoberfest-accepted

#383 Added python code for 15th October problem
  2022-Oct/15 Oct 2022/Kratos.py
Labels: hacktoberfest-accepted

#477 Create Pratik_shinde7.py
  2022-Oct/07 Oct 2022/Pratik_shinde7.py
Labels: hacktoberfest-accepted

#478 Create Huzaifa_Shaikh6.py
  2022-Oct/06 Oct 2022/Huzaifa6.py.py
Labels: hacktoberfest-accepted

#479 Create Pratik_shinde8.java
  2022-Oct/08 Oct 2022/Pratik_shinde8.java
Labels: hacktoberfest-accepted

#457 Nandhika.java
  2022-Oct/18 Oct 2022/Nandhika.java
Labels: hacktoberfest-accepted

#468 21 oct Created By Mayank Sahu
  2022-Oct/21 Oct 2022/Mayank_Sahu.cpp
Labels: hacktoberfest-accepted

#435 Add solution Oct 18
  2022-Oct/01 Oct 2022/atharva_pardeshi.js
  2022-Oct/02 Oct 2022/atharva_pardeshi.js
  2022-Oct/18 Oct 2022/atharva_pardeshi.js
Labels: hacktoberfest-accepted

#472 Create Sourabh_Dalal.js
  2022-Oct/21 Oct 2022/Sourabh_Dalal.js
Labels: hacktoberfest-accepted

#480 create Huzaifa7.py
  2022-Oct/07 Oct 2022/huzaifa7.py
Labels: hacktoberfest-accepted

#483 Create Huzaifa shaikh9.java
  2022-Oct/09 Oct 2022/Huzaifa_shaikh9.java
Labels: hacktoberfest-accepted

#488 "21 oct 2022 Created by Kratik Jain in c++"
  2022-Oct/21 Oct 2022/Kratik_Jain.cpp
Labels: hacktoberfest-accepted

#492 created by shantanu chinchle
  2022-Oct/15 Oct 2022/chinchle-shantanu.c
  2022-Oct/16 Oct 2022/chinchle-shantanu.c
  2022-Oct/18 Oct 2022/chinchle-shantanu.c
Labels: hacktoberfest-accepted

#493 Add files via upload
  2022-Oct/21 Oct 2022/Debarghya.java
Labels: hacktoberfest-accepted

#491 Create Mahendra_Bagul.cpp
  2022-Oct/21 Oct 2022/Mahendra_Bagul.cpp
Labels: hacktoberfest-accepted

#498 Add files via upload
  2022-Oct/01 Oct 2022/Debarghya.sh
Labels: hacktoberfest-accepted

#415 created by mohee athani
  2022-Oct/13 Oct 2022/mohee_athani.py
  2022-Oct/16 Oct 2022/mohee_athani.cpp
Labels: hacktoberfest-accepted

#505 23priya
  2022-Oct/08 Oct 2022/priyanka_kothule.cpp
  2022-Oct/11 Oct 2022/priyanka_kothule.cpp
  2022-Oct/13 Oct 2022/priyanka_kothule.cpp
  2022-Oct/15 Oct 2022/priyanka_kothule.java
  2022-Oct/16 Oct 2022/priyanka_kothule.cpp
  2022-Oct/18 Oct 2022/priyanka_kothule.cpp
  2022-Oct/21 Oct 2022/priyanka_kothule.cpp
Labels: hacktoberfest-accepted

#506 priyanka_kothule.java
  2022-Oct/09 Oct 2022/priyanka_kothule.java
Labels: hacktoberfest-accepted

#508 Solution for Oct 03
  2022-Oct/03 Oct 2022/atharva_pardeshi.js
Labels: hacktoberfest-accepted

#507 Solution for the problem Statement
  2022-Oct/21 Oct 2022/Mohit.cpp
Labels: hacktoberfest-accepted

#499 Create Mohammed_Amaan_Khan.cpp
  2022-Oct/01 Oct 2022/Mohammed_Amaan_Khan.cpp
  2022-Oct/02 Oct 2022/Mohammed_Amaan_Khan.cpp
Labels: hacktoberfest-accepted

#485 Create Sai_Chouhan.py
  2022-Oct/18 Oct 2022/Sai_Chouhan.py
Labels: hacktoberfest-accepted

#426 Added Cpp solution for problem 18/10/22
  2022-Oct/18 Oct 2022/justin_roy.cpp
Labels: hacktoberfest-accepted

#469 Multiplication Created by devzohaib
  2022-Oct/21 Oct 2022/dev_zohaib.py
Labels: hacktoberfest-accepted

#413 Added golang code for 16th october problem statement.
  2022-Oct/16 Oct 2022/Nikit.go
Labels: hacktoberfest-accepted

#432 Create Pratik_Kumar.cpp
  2022-Oct/16 Oct 2022/Pratik_Kumar.cpp
Labels: hacktoberfest-accepted

#430 Add files via upload
  2022-Oct/12 Oct 2022/Vishal_chavhan.py
  2022-Oct/18 Oct 2022/Vishal_Chavhan.py
Labels: hacktoberfest-accepted

#424 Renamed files name
  2022-Oct/15 Oct 2022/SurajKumar_Kushwaha.cpp
  2022-Oct/16 Oct 2022/Raghvendra_Tiwari.C
  2022-Oct/16 Oct 2022/Rati_Jindal.java
  2022-Oct/16 Oct 2022/Tanya_Ahuja.cpp
Labels: hacktoberfest-accepted

#497 added solution
  2022-Oct/21 Oct 2022/Ayush Srivastava.cpp
Labels: hacktoberfest-accepted

#439 Create Manibhushan_Kumar.cpp
  2022-Oct/15 Oct 2022/Manibhushan_Kumar.cpp
Labels: hacktoberfest-accepted

#440 Create PriyanshuBal.cpp
  2022-Oct/15 Oct 2022/PriyanshuBal.cpp
Labels: hacktoberfest-accepted

#504 Matrix multiplication created by Moses Rukshan
  2022-Oct/11 Oct 2022/Moses_Rukshan.py
  2022-Oct/21 Oct 2022/Moses_Rukshan.py
Labels: hacktoberfest-accepted

#501 Completed matrix multiplication problem
  2022-Oct/21 Oct 2022/raj_kumar.cpp
Labels: hacktoberfest-accepted
